# Generated by Django 4.2.9 on 2024-01-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projeekle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proje",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects_as_member",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Üyeler",
            ),
        ),
        migrations.AlterField(
            model_name="proje",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Projeyi Oluşturan",
            ),
        ),
    ]
