# Generated by Django 4.2.9 on 2024-01-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0004_rename_project_task_proje"),
    ]

    operations = [
        migrations.RemoveField(model_name="proje", name="members",),
    ]
