# Generated by Django 4.2.9 on 2024-01-06 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projeekle", "0006_proje_members"),
    ]

    operations = [
        migrations.RemoveField(model_name="proje", name="members",),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeekle.proje",
                        verbose_name="Proje",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grup",
                "verbose_name_plural": "Gruplar",
                "unique_together": {("proje", "user")},
            },
        ),
    ]
