# Generated by Django 4.2.9 on 2024-01-06 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projeekle", "0007_remove_proje_members_group"),
    ]

    operations = [
        migrations.AlterModelOptions(name="group", options={},),
        migrations.AlterUniqueTogether(name="group", unique_together=set(),),
        migrations.RemoveField(model_name="group", name="user",),
        migrations.AddField(
            model_name="group",
            name="user",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Kullanıcı"
            ),
        ),
    ]
