# Generated by Django 4.2.9 on 2024-01-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0008_alter_group_options_alter_group_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proje",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proje_group",
                to="projeekle.group",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="proje",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_proje",
                to="projeekle.proje",
                verbose_name="Proje",
            ),
        ),
    ]
