# Generated by Django 4.2.9 on 2024-01-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0010_group_groupname"),
    ]

    operations = [
        migrations.RemoveField(model_name="group", name="proje",),
    ]
