# Generated by Django 4.2.9 on 2024-01-07 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projeekle", "0011_remove_group_proje"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atanan Kişi",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Bitiş Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Başlangıç Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Tamamlancak", "Tamamlancak"),
                    ("Devam Ediyor", "Devam Ediyor"),
                    ("Tamamlandı", "Tamamlandı"),
                ],
                default="Tamamlanacak",
                max_length=20,
                verbose_name="Görev Durumu",
            ),
        ),
    ]
