# Generated by Django 4.2.9 on 2024-01-10 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projeekle", "0013_task_description_assignedtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="proje",
            name="users",
            field=models.ManyToManyField(
                default="Varsayılan Kişiler",
                related_name="membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Üyeler",
            ),
        ),
    ]
