# Generated by Django 4.2.9 on 2024-01-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0015_remove_proje_group_delete_group"),
    ]

    operations = [
        migrations.DeleteModel(name="AssignedTask",),
    ]
