# Generated by Django 4.2.9 on 2024-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0016_delete_assignedtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proje",
            name="content",
            field=models.TextField(max_length=8200, verbose_name="İçerik"),
        ),
    ]
