# Generated by Django 4.2.9 on 2024-01-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0017_alter_proje_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Tamamlancak", "Tamamlancak"),
                    ("Devam Ediyor", "Devam Ediyor"),
                    ("Tamamlandı", "Tamamlandı"),
                    ("Gecikti", "Gecikti"),
                ],
                default="Tamamlanacak",
                max_length=20,
                verbose_name="Görev Durumu",
            ),
        ),
    ]
