# Generated by Django 4.2.9 on 2024-01-12 08:37

import datetime
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0018_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="delay_time",
            field=models.DateTimeField(
                default=timezone.now, verbose_name="Gecikme Süresi"
            ),
        ),
    ]
