# Generated by Django 4.2.9 on 2024-01-12 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeekle", "0019_task_delay_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="delay_time",
            field=models.DateTimeField(
                default=datetime.timedelta, verbose_name="Gecikme Süresi"
            ),
        ),
    ]
