# Generated by Django 4.2.9 on 2024-01-18 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projeekle", "0022_alter_proje_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proje",
            name="users",
            field=models.ManyToManyField(
                related_name="membership",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Üyeler",
            ),
        ),
    ]
