# Generated by Django 4.2.9 on 2024-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="job",
            field=models.TextField(
                default="Varsayılan Meslek", max_length=40, verbose_name="Meslek"
            ),
        ),
    ]
